import Head from "next/head";
import LoginForm from "../components/login/login_form";
export default function DoctorLogin() {
  return (
    <section>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm />
    </section>
  );
}
