import Head from "next/head";
import PatientRegistrationForm from "../components/registration/registration_form";

export default function Registration() {
  return (
    <section>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PatientRegistrationForm />
    </section>
  );
}
